version: '3.7'
services:
    web:
        build: .
        #container_name: "php74-1"
        volumes:
            - "./html/:/var/www/html"
        privileged: true
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: mysql:8
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./config/mysql/init:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: hogehoge
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
            - "4306:3306"
        #container_name: mysql8-1